coder:
  env:
    - name: CODER_PG_CONNECTION_URL
      value: "postgres://coder:coder123@coder-postgres-postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable"
    - name: CODER_ACCESS_URL
      value: "http://localhost:3000"
  service:
    type: ClusterIP
